export enum UserRole {
	BUYER = 'BUYER',
	SELLER = 'SELLER',
	ADMIN = 'ADMIN',
	SHIPPER = 'SHIPPER',
}

export enum ProductStatus {
	AVAILABLE = 'AVAILABLE',
	HIDDEN = 'HIDDEN',
	OUT_OF_STOCK = 'OUT_OF_STOCK',
	PENDING = 'PENDING',
}

export enum OrderStatus {
	PENDING_PAYMENT = 'PENDING_PAYMENT',
	PAID = 'PAID',
	WAITING_SELLER_CONFIRMATION = 'WAITING_SELLER_CONFIRMATION',
	SELLER_CONFIRMED = 'SELLER_CONFIRMED',
	SHIPPING = 'SHIPPING',
	DELIVERED = 'DELIVERED',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
	RETURN_REQUESTED = 'RETURN_REQUESTED',
	REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
	ONLINE = 'ONLINE',
	COD = 'COD',
}

export enum PaymentStatus {
	PENDING = 'PENDING',
	WAITING_COD_COLLECTION = 'WAITING_COD_COLLECTION',
	WAITING_ONLINE_PAYMENT = 'WAITING_ONLINE_PAYMENT',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	REFUNDED = 'REFUNDED',
}

export enum ShipmentStatus {
	CREATED = 'CREATED',
	PICKED_UP = 'PICKED_UP',
	IN_TRANSIT = 'IN_TRANSIT',
	DELIVERED = 'DELIVERED',
	RETURNED = 'RETURNED',
}

export enum ReturnStatus {
	REQUESTED = 'REQUESTED',
	APPROVED = 'APPROVED',
	REJECTED = 'REJECTED',
	COMPLETED = 'COMPLETED',
}

export enum WalletTransactionType {
	TOP_UP = 'TOP_UP',
	ORDER_PAYMENT = 'ORDER_PAYMENT',
	REFUND = 'REFUND',
	WITHDRAW = 'WITHDRAW',
	COMMISSION = 'COMMISSION',
}

